title: Gabriele Polastri
author: 
description: >- Blog about my projects/career

remote_theme: "daattali/beautiful-jekyll"


avatar: /assets/images/tuo-avatar.jpg # Percorso a un'immagine per il tuo profilo (opzionale)

 github: gabrielepol 

navbar-links:
  About Me: "/aboutme"
  Progetti: "/projects"
