title: "Gabriele Polastri"
description: "Hi, I'm Gabriele and I'm a first-year Computer Science student at Sapienza University."


remote_theme: wowthemesnet/affiliate-jekyll-theme

plugins:
  - jekyll-remote-theme
