
title: Gabriele Polastri
author: Gabriele Polastri
description: >-
  Blog about my projects and career

remote_theme: "daattali/beautiful-jekyll"

avatar: /assets/images/tuo-avatar.jpg

social-network-links:
  github: gabrielepol


  About Me: "/aboutme"
  Progetti: "/projects"
